# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.define "elk-docker" do |node|
    node.vm.hostname = "elk-docker"
    node.vm.network "forwarded_port", guest: 5601, host: 5601
    node.vm.network "forwarded_port", guest: 9000, host: 9000
    node.vm.network "forwarded_port", guest: 9200, host: 9200
    node.vm.network "forwarded_port", guest: 25826, host: 25826
    node.vm.provision :shell, path: "bootstrap.sh"
    node.vm.provision "docker" do |d|
      d.run "elasticsearch",
        args: "-v /data/elasticsearch:/usr/share/elasticsearch/data -p 9200:9200"
      d.run "logstash",
        args: "--link elasticsearch:db -v /vagrant/conf:/conf -p 25826:25826 -p 25826:25826/udp",
        cmd: "logstash -f /conf/syslog.conf"
      d.run "vfarcic/bdd",
        args: "-p 9000:9000 --log-driver=syslog -v /etc/localtime:/etc/localtime:ro"
      d.run "vfarcic/kibana",
        args: "-p 5601:5601 --link elasticsearch:db"
    end
    node.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end
end
